[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "OTalign"
version = "0.0.1"
description = "Differentiable OT-based alignment and evaluation for protein embeddings"
authors = [{ name = "Minsoo Kim" }]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "torch (>=2.5.1,<3.0.0)",
    "numpy (==2.2.6)",
    "scipy (>=1.16.2,<2.0.0)",
    "pandas (>=2.3.2,<3.0.0)",
    "huggingface-hub (>=0.34.5,<0.35.0)",
    "transformers (>=4.56.1,<5.0.0)",
    "accelerate (>=1.10.1,<2.0.0)",
    "sentencepiece (>=0.2.1,<0.3.0)",
    "datasets (>=4.0.0,<5.0.0)",
    "evaluate (>=0.4.5,<0.5.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "matplotlib (>=3.10.6,<4.0.0)",
    "scikit-learn (>=1.7.2,<2.0.0)",
    "pot (>=0.9.5,<0.10.0)",
    "ipykernel (>=6.30.1,<7.0.0)",
    "ipywidgets (>=8.1.7,<9.0.0)",
    "wandb (>=0.21.4,<0.22.0)",
    "numba (>=0.61.2,<0.62.0)",
    "scikit-image (>=0.25.2,<0.26.0)",
    "lmdb (>=1.4.1,<2.0.0)",
    "peft (>=0.17.1,<0.18.0)",
    "deepspeed (==0.17.5)",
    "torchvision (>=0.23.0,<0.24.0)",
    "seaborn",
]

[project.optional-dependencies]
deepblast = ["deepblast"]
dev = ["pytest", "ruff", "pre-commit"]

[tool.ruff]
line-length = 199

# Exclude the following files and directories.
exclude = [
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    "_build",
    "buck-out",
    "build",
    "dist",
    "env",
    "venv",
]

[tool.ruff.lint]
# Never enforce `E501` (line length violations).
ignore = ["C901", "E501", "E402", "W293"]
select = ["C", "E", "F", "I", "W"]

# Ignore import violations in all `__init__.py` files.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.setuptools]
packages = ["otalign"]
