#!/usr/bin/env python3
"""
Ablation Study for OTalign Gap Penalties

This script conducts an ablation study on the OTalign model, focusing on the
contribution of different components in the dynamic gap penalty calculation
from Unbalanced Optimal Transport (UOT) plans.

Experiments:
  1. Fixed vs. Dynamic Gap Penalties
  2. Gap Penalty Information Sources (marginal mass vs. dual potentials)
  3. Hyperparameter Sensitivity (gamma, k_f/k_g, score_scale)

Requires pre-computed transport plans (generated by run_otalign_on_dataset.py
with --save_transport_plan_dir).

Example usage:
  python scripts/run_ablation_study.py \
    --dataset DeepFoldProtein/SABmark-dataset,sup,test \
    --transport_plan_dir out/results/sabmark_sup/otalign_esm1b_lora_ft2_2/transport_plans

Example output:
  Ablation Study Results (SABmark-sup, 19092 pairs)
  ┌────────────────────────────┬──────────────┬──────────┐
  │ Configuration              │ Mean F1 Score│ % Change │
  ├────────────────────────────┼──────────────┼──────────┤
  │ OTalign (Full Model)       │ 0.417        │  0.0%    │
  │ Exp 1: Fixed Gaps          │ 0.390        │ -6.5%    │
  │ Exp 2a: Mass Only          │ 0.412        │ -1.2%    │
  │ Exp 2b: Duals Only         │ 0.395        │ -5.3%    │
  │ Exp 3: gamma = 0.5         │ 0.414        │ -0.7%    │
  │ Exp 3: gamma = 2.0         │ 0.410        │ -1.7%    │
  │ Exp 3: k_f = k_g = 0.0     │ 0.412        │ -1.2%    │
  │ Exp 3: k_f = k_g = 1.5     │ 0.409        │ -1.9%    │
  │ Exp 3: score_scale = 0.5   │ 0.401        │ -3.8%    │
  │ Exp 3: score_scale = 2.0   │ 0.415        │ -0.5%    │
  └────────────────────────────┴──────────────┴──────────┘
  (Values above are illustrative; actual results depend on your model/dataset.)
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from tqdm.auto import tqdm


# Ensure project root is on the path
project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from otalign.align.uot_alignment import hard_alignment_from_transport
from otalign.quantize import dequantize
from scripts.dataset_utils import iter_pairs_from_dataset


# ---------------------------------------------------------------------------
# Evaluation metric
# ---------------------------------------------------------------------------


def calculate_f1(predicted_path, true_matches):
    """Calculate precision, recall, and F1 score for a predicted alignment."""
    predicted_matches = {(q - 1, t - 1) for q, t, op in predicted_path if op == "M"}

    if not predicted_matches and not true_matches:
        return 1.0, 1.0, 1.0

    tp = len(predicted_matches & true_matches)
    fp = len(predicted_matches - true_matches)
    fn = len(true_matches - predicted_matches)

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

    return precision, recall, f1


# ---------------------------------------------------------------------------
# Experiment definitions
# ---------------------------------------------------------------------------


def run_experiment_full_model(P, f, g, **kwargs):
    """Standard OTalign model with all components."""
    kwargs["mode"] = "glocal"
    return hard_alignment_from_transport(P, f=f, g=g, **kwargs)


def run_experiment_fixed_gaps(P, **kwargs):
    """Exp 1: Fixed gap penalties (no dynamic components)."""
    kwargs["gamma"] = 0.0
    kwargs["mode"] = "glocal"
    return hard_alignment_from_transport(P, f=None, g=None, **kwargs)


def run_experiment_mass_only(P, **kwargs):
    """Exp 2a: Use only marginal mass for gap penalties."""
    kwargs["mode"] = "glocal"
    return hard_alignment_from_transport(P, f=None, g=None, **kwargs)


def run_experiment_duals_only(P, f, g, **kwargs):
    """Exp 2b: Use only dual potentials for gap penalties."""
    kwargs["gamma"] = 0.0
    kwargs["mode"] = "glocal"
    return hard_alignment_from_transport(P, f=f, g=g, **kwargs)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------


def load_data(dataset_id, transport_plan_dir):
    """Load dataset pairs and their pre-computed transport plans."""
    transport_plan_dir = Path(transport_plan_dir)
    if not transport_plan_dir.exists():
        raise FileNotFoundError(f"Transport plan directory not found: {transport_plan_dir}\nPlease run the benchmark first with --save_transport_plan_dir.")

    dataset_iterator = iter_pairs_from_dataset(dataset_id)
    all_data = []

    print(f"Loading data from {transport_plan_dir}...")
    for item in tqdm(list(dataset_iterator)):
        pair_id = item.get("pair_id", f"{item['seq1_id']}-{item['seq2_id']}")
        plan_path = transport_plan_dir / f"{pair_id}.npz"

        if plan_path.exists():
            try:
                data = np.load(plan_path, allow_pickle=True)
                quantized_plan_data = {
                    "data": data["data"],
                    "scale": data["scale"],
                    "zero_point": data["zero_point"],
                }
                all_data.append(
                    {
                        "pair_id": pair_id,
                        "P": dequantize(quantized_plan_data),
                        "f": data["f"],
                        "g": data["g"],
                        "true_matches": {tuple(x) for x in item["ref_alignment"]},
                    }
                )
            except Exception as e:
                print(f"Warning: Could not load {plan_path}: {e}")

    print(f"Successfully loaded {len(all_data)} pairs with transport plans.")
    return all_data


# ---------------------------------------------------------------------------
# Main ablation study
# ---------------------------------------------------------------------------


def run_ablation(all_data, go_base, ge_base, gamma, k_f, k_g, score_scale, gammas, ks, scales):
    """Run all ablation experiments and return a DataFrame of results."""
    default_params = {
        "go_base": go_base,
        "ge_base": ge_base,
        "gamma": gamma,
        "k_f": k_f,
        "k_g": k_g,
        "score_scale": score_scale,
    }

    results = []
    for item in tqdm(all_data, desc="Running experiments"):
        P = item["P"]
        f = item["f"]
        g = item["g"]
        true_matches = item["true_matches"]
        pair_id = item["pair_id"]

        # Full model
        aln = run_experiment_full_model(P, f, g, **default_params)
        _, _, f1 = calculate_f1(aln["path"], true_matches)
        results.append({"pair": pair_id, "config": "OTalign (Full Model)", "f1": f1})

        # Exp 1: Fixed gaps
        aln = run_experiment_fixed_gaps(P, **default_params)
        _, _, f1 = calculate_f1(aln["path"], true_matches)
        results.append({"pair": pair_id, "config": "Exp 1: Fixed Gaps", "f1": f1})

        # Exp 2a: Mass only
        aln = run_experiment_mass_only(P, **default_params)
        _, _, f1 = calculate_f1(aln["path"], true_matches)
        results.append({"pair": pair_id, "config": "Exp 2a: Mass Only", "f1": f1})

        # Exp 2b: Duals only
        aln = run_experiment_duals_only(P, f, g, **default_params)
        _, _, f1 = calculate_f1(aln["path"], true_matches)
        results.append({"pair": pair_id, "config": "Exp 2b: Duals Only", "f1": f1})

        # Exp 3: Hyperparameter sensitivity
        for g_val in gammas:
            params = {**default_params, "gamma": g_val}
            aln = run_experiment_full_model(P, f, g, **params)
            _, _, f1 = calculate_f1(aln["path"], true_matches)
            results.append({"pair": pair_id, "config": f"Exp 3: gamma = {g_val}", "f1": f1})

        for k_val in ks:
            params = {**default_params, "k_f": k_val, "k_g": k_val}
            aln = run_experiment_full_model(P, f, g, **params)
            _, _, f1 = calculate_f1(aln["path"], true_matches)
            results.append({"pair": pair_id, "config": f"Exp 3: k_f = k_g = {k_val}", "f1": f1})

        for s_val in scales:
            params = {**default_params, "score_scale": s_val}
            aln = run_experiment_full_model(P, f, g, **params)
            _, _, f1 = calculate_f1(aln["path"], true_matches)
            results.append({"pair": pair_id, "config": f"Exp 3: score_scale = {s_val}", "f1": f1})

    return pd.DataFrame(results)


def summarize_results(results_df):
    """Aggregate per-pair results into a summary table."""
    summary = results_df.groupby("config")["f1"].mean().reset_index()

    base_f1 = summary.loc[summary["config"] == "OTalign (Full Model)", "f1"]
    if not base_f1.empty:
        base_f1 = base_f1.iloc[0]
        summary["% Change"] = summary["f1"].apply(lambda x: f"{(x - base_f1) / base_f1 * 100:+.1f}%" if base_f1 > 0 else "N/A")
    else:
        summary["% Change"] = "N/A"

    summary.rename(columns={"config": "Configuration", "f1": "Mean F1 Score"}, inplace=True)

    config_order = [
        "OTalign (Full Model)",
        "Exp 1: Fixed Gaps",
        "Exp 2a: Mass Only",
        "Exp 2b: Duals Only",
    ]
    # Add dynamic configs based on what's present
    for col in summary["Configuration"]:
        if col.startswith("Exp 3:") and col not in config_order:
            config_order.append(col)

    summary["Configuration"] = pd.Categorical(summary["Configuration"], categories=config_order, ordered=True)
    summary = summary.sort_values("Configuration")
    summary["Mean F1 Score"] = summary["Mean F1 Score"].map("{:.3f}".format)

    return summary


def main():
    parser = argparse.ArgumentParser(
        description="Run OTalign ablation study on gap penalty components.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--dataset",
        type=str,
        required=True,
        help="Dataset identifier (e.g., DeepFoldProtein/SABmark-dataset,sup,test).",
    )
    parser.add_argument(
        "--transport_plan_dir",
        type=str,
        required=True,
        help="Directory containing pre-computed transport plans (.npz files).",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Optional path to save per-pair results as CSV.",
    )

    # Default hyperparameters
    parser.add_argument("--go_base", type=float, default=8.0, help="Base gap open penalty (default: 8.0).")
    parser.add_argument("--ge_base", type=float, default=1.0, help="Base gap extend penalty (default: 1.0).")
    parser.add_argument("--gamma", type=float, default=1.0, help="Mass sensitivity exponent (default: 1.0).")
    parser.add_argument("--k_f", type=float, default=0.75, help="Dual potential sensitivity for query (default: 0.75).")
    parser.add_argument("--k_g", type=float, default=0.75, help="Dual potential sensitivity for template (default: 0.75).")
    parser.add_argument("--score_scale", type=float, default=1.0, help="Match score scaling factor (default: 1.0).")

    # Sweep values for Experiment 3
    parser.add_argument(
        "--gammas",
        type=float,
        nargs="+",
        default=[0.5, 2.0],
        help="Gamma values to sweep (default: 0.5 2.0).",
    )
    parser.add_argument(
        "--ks",
        type=float,
        nargs="+",
        default=[0.0, 1.5],
        help="k_f/k_g values to sweep (default: 0.0 1.5).",
    )
    parser.add_argument(
        "--scales",
        type=float,
        nargs="+",
        default=[0.5, 2.0],
        help="score_scale values to sweep (default: 0.5 2.0).",
    )

    args = parser.parse_args()

    # Load data
    all_data = load_data(args.dataset, args.transport_plan_dir)
    if not all_data:
        print("ERROR: No data loaded. Check your dataset and transport plan directory.")
        sys.exit(1)

    # Run ablation
    results_df = run_ablation(
        all_data,
        go_base=args.go_base,
        ge_base=args.ge_base,
        gamma=args.gamma,
        k_f=args.k_f,
        k_g=args.k_g,
        score_scale=args.score_scale,
        gammas=args.gammas,
        ks=args.ks,
        scales=args.scales,
    )

    # Summarize and print
    summary = summarize_results(results_df)
    dataset_name = args.dataset.split("/")[-1].split(",")[0] if "/" in args.dataset else args.dataset
    print(f"\nAblation Study Results ({dataset_name}, {len(all_data)} pairs)")
    print(summary.to_string(index=False))

    # Save per-pair results if requested
    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        results_df.to_csv(out_path, index=False)
        print(f"\nPer-pair results saved to {out_path}")


if __name__ == "__main__":
    main()
