import { LeaderboardData } from "./types";

export const leaderboardData: LeaderboardData = {
  leaderboard_data: [
    {
      rank: 1,
      model: "OTalign (AnkhCL)",
      type: "OTalign",
      description: "Optimal Transport alignment with AnkhCL embeddings",
      paper_url: "",
      code_url: "https://github.com/DeepFoldProtein/OTalign",
      parameters: "1.15B",
      average: 0.5027,
      malidup_f1: 0.6396,
      malisam_f1: 0.1911,
      sabmark_sup_recall: 0.7139,
      sabmark_twi_recall: 0.466,
      date_submitted: "2025-09-19",
      organization: "DeepFold",
    },
    {
      rank: 2,
      model: "OTalign (ProtT5_XL_Uniref50)",
      type: "OTalign",
      description: "Optimal Transport alignment with ProtT5_XL_Uniref50 embeddings",
      paper_url: "",
      code_url: "https://github.com/DeepFoldProtein/OTalign",
      parameters: "3B",
      average: 0.4753,
      malidup_f1: 0.5904,
      malisam_f1: 0.2011,
      sabmark_sup_recall: 0.6783,
      sabmark_twi_recall: 0.4313,
      date_submitted: "2025-09-19",
      organization: "DeepFold",
    },
    {
      rank: 3,
      model: "OTalign (ESM-2 650M)",
      type: "OTalign",
      description: "Optimal Transport alignment with ESM-2 650M embeddings",
      paper_url: "",
      code_url: "https://github.com/DeepFoldProtein/OTalign",
      parameters: "650M",
      average: 0.4212,
      malidup_f1: 0.5391,
      malisam_f1: 0.1133,
      sabmark_sup_recall: 0.6499,
      sabmark_twi_recall: 0.3824,
      date_submitted: "2025-09-19",
      organization: "DeepFold",
    },
    {
      rank: 4,
      model: "OTalign (ESM-2 150M)",
      type: "OTalign",
      description: "Optimal Transport alignment with ESM-2 150M embeddings",
      paper_url: "",
      code_url: "https://github.com/DeepFoldProtein/OTalign",
      parameters: "150M",
      average: 0.4058,
      malidup_f1: 0.5187,
      malisam_f1: 0.107,
      sabmark_sup_recall: 0.631,
      sabmark_twi_recall: 0.3666,
      date_submitted: "2025-09-19",
      organization: "DeepFold",
    },
    {
      rank: 5,
      model: "OTalign (ESM-2 12M)",
      type: "OTalign",
      description: "Optimal Transport alignment with ESM-2 12M embeddings",
      paper_url: "",
      code_url: "https://github.com/DeepFoldProtein/OTalign",
      parameters: "35M",
      average: 0.3757,
      malidup_f1: 0.4629,
      malisam_f1: 0.1078,
      sabmark_sup_recall: 0.5914,
      sabmark_twi_recall: 0.3408,
      date_submitted: "2025-09-19",
      organization: "DeepFold",
    },
    {
      rank: 6,
      model: "OTalign (ESM-2 3B)",
      type: "OTalign",
      description: "Optimal Transport alignment with ESM-2 3B embeddings",
      paper_url: "",
      code_url: "https://github.com/DeepFoldProtein/OTalign",
      parameters: "3B",
      average: 0.3592,
      malidup_f1: 0.4844,
      malisam_f1: 0.0764,
      sabmark_sup_recall: 0.5718,
      sabmark_twi_recall: 0.3041,
      date_submitted: "2025-09-19",
      organization: "DeepFold",
    },
    {
      rank: 7,
      model: "OTalign (ESM-2 8M)",
      type: "OTalign",
      description: "Optimal Transport alignment with ESM-2 8M embeddings",
      paper_url: "",
      code_url: "https://github.com/DeepFoldProtein/OTalign",
      parameters: "8M",
      average: 0.3205,
      malidup_f1: 0.4024,
      malisam_f1: 0.1114,
      sabmark_sup_recall: 0.5025,
      sabmark_twi_recall: 0.2657,
      date_submitted: "2025-09-19",
      organization: "DeepFold",
    },
    {
      rank: 8,
      model: "OTalign (ESM-1b)",
      type: "OTalign",
      description: "Optimal Transport alignment with ESM-1b embeddings",
      paper_url: "",
      code_url: "https://github.com/DeepFoldProtein/OTalign",
      parameters: "650M",
      average: 0.3069,
      malidup_f1: 0.4149,
      malisam_f1: 0.0633,
      sabmark_sup_recall: 0.5,
      sabmark_twi_recall: 0.2492,
      date_submitted: "2025-09-19",
      organization: "DeepFold",
    },
    {
      rank: 9,
      model: "Needleman-Wunsch",
      type: "Traditional",
      description: "Dynamic programming with substitution matrices",
      paper_url: "https://doi.org/10.1016/0022-2836(70)90057-4",
      code_url: "https://zhanggroup.org/NW-align/",
      parameters: "N/A",
      average: 0.2378,
      malidup_f1: 0.3492,
      malisam_f1: 0.0662,
      sabmark_sup_recall: 0.3861,
      sabmark_twi_recall: 0.1496,
      date_submitted: "2025-09-19",
      organization: "Zhang Lab",
    },
    {
      rank: 10,
      model: "HHAlign",
      type: "Traditional",
      description: "Profile-profile alignment with MSAs",
      paper_url: "https://doi.org/10.1093/bioinformatics/bti125",
      code_url: "https://github.com/soedinglab/hh-suite",
      parameters: "N/A",
      average: 0.2255,
      malidup_f1: 0.3825,
      malisam_f1: 0.0092,
      sabmark_sup_recall: 0.3507,
      sabmark_twi_recall: 0.1596,
      date_submitted: "2025-09-19",
      organization: "Söding Lab",
    },
  ],
  metadata: {
    last_updated: "2025-09-19T17:18:16Z",
    total_models: 10,
    datasets: ["MALIDUP", "MALISAM", "SABmark"],
    metrics: ["F1 Score", "Recall"],
    version: "1.0.0",
  },
};
