import { LeaderboardData } from "./types";

export const leaderboardData: LeaderboardData = {
  leaderboard_data: [
    {
      rank: 1,
      model: "HHAlign",
      type: "Traditional",
      description: "Profile-profile alignment with MSAs",
      paper_url: "https://doi.org/10.1093/bioinformatics/bti125",
      code_url: "https://github.com/soedinglab/hh-suite",
      average_f1: 0.1958,
      malidup_f1: 0.3825,
      malisam_f1: 0.0092,
      sabmark_sup_recall: 0.3507,
      sabmark_twi_recall: 0.1596,
      malidup_recall: 0.4111,
      malisam_recall: 0.01,
      date_submitted: "2025-09-18",
      organization: "Söding Lab",
    },
    {
      rank: 2,
      model: "Needleman-Wunsch",
      type: "Traditional",
      description: "Dynamic programming with substitution matrices",
      paper_url: "https://doi.org/10.1016/0022-2836(70)90057-4",
      code_url: "https://zhanggroup.org/NW-align/",
      average_f1: 0.2077,
      malidup_f1: 0.3492,
      malisam_f1: 0.0662,
      sabmark_sup_recall: 0.3861,
      sabmark_twi_recall: 0.1496,
      malidup_recall: 0.3733,
      malisam_recall: 0.0749,
      date_submitted: "2025-09-18",
      organization: "Zhang Lab",
    },
    {
      rank: 3,
      model: "OTalign (ESM-2)",
      type: "OTalign",
      description: "Optimal Transport alignment with ESM-2 embeddings",
      paper_url: "",
      code_url: "https://github.com/your-username/OTalign",
      average_f1: null,
      malidup_f1: null,
      malisam_f1: null,
      sabmark_sup_recall: null,
      sabmark_twi_recall: null,
      malidup_recall: null,
      malisam_recall: null,
      date_submitted: "2025-01-15",
      organization: "DeepFold",
    },
    {
      rank: 4,
      model: "OTalign (ESM-1b)",
      type: "OTalign",
      description: "Optimal Transport alignment with ESM-1b embeddings",
      paper_url: "",
      code_url: "https://github.com/your-username/OTalign",
      average_f1: null,
      malidup_f1: null,
      malisam_f1: null,
      sabmark_sup_recall: null,
      sabmark_twi_recall: null,
      malidup_recall: null,
      malisam_recall: null,
      date_submitted: "2025-01-15",
      organization: "DeepFold",
    },
    {
      rank: 5,
      model: "OTalign (ProtT5)",
      type: "OTalign",
      description: "Optimal Transport alignment with ProtT5 embeddings",
      paper_url: "",
      code_url: "https://github.com/your-username/OTalign",
      average_f1: null,
      malidup_f1: null,
      malisam_f1: null,
      sabmark_sup_recall: null,
      sabmark_twi_recall: null,
      malidup_recall: null,
      malisam_recall: null,
      date_submitted: "2025-01-15",
      organization: "DeepFold",
    },
    {
      rank: 6,
      model: "OTalign (AnkhCL)",
      type: "OTalign",
      description: "Optimal Transport alignment with AnkhCL embeddings",
      paper_url: "",
      code_url: "https://github.com/your-username/OTalign",
      average_f1: null,
      malidup_f1: null,
      malisam_f1: null,
      sabmark_sup_recall: null,
      sabmark_twi_recall: null,
      malidup_recall: null,
      malisam_recall: null,
      date_submitted: "2025-01-15",
      organization: "DeepFold",
    },
  ],
  metadata: {
    last_updated: "2025-09-18T10:00:00Z",
    total_models: 6,
    datasets: ["MALIDUP", "MALISAM", "SABmark"],
    metrics: ["F1 Score", "Recall"],
    version: "1.0.0",
  },
};
